// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// psiteCal
NumericVector psiteCal(CharacterVector cigar, IntegerVector start, IntegerVector psitemap);
RcppExport SEXP _RiboDiPA_psiteCal(SEXP cigarSEXP, SEXP startSEXP, SEXP psitemapSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type cigar(cigarSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type start(startSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type psitemap(psitemapSEXP);
    rcpp_result_gen = Rcpp::wrap(psiteCal(cigar, start, psitemap));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RiboDiPA_psiteCal", (DL_FUNC) &_RiboDiPA_psiteCal, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_RiboDiPA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
